#!/usr/bin/python
# -*- coding: utf-8 -*-

# Usage: cat <file> | python client.py
# Example line of the input file: 127.0.0.1 20130101
# Note: the last parameter (the day) is optional,
#       the default value is the last imported day
# The output of the script is: 127.0.0.1 3303 20130101

import fileinput

from ip_asn_history import api as ip2asn


if __name__ == '__main__':
    for line in fileinput.input():
        line = line.strip()
        if not len(line) > 0:
            continue
        splitted = line.split()
        if len(splitted) > 1:
            ip, date = splitted
        else:
            ip, date = [line, ip2asn.default_announce_date]
        ip2asn.prepare_keys(ip)
        print ip, ip2asn.asn_date(date), date
