#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse

from ip_asn_history import api as ip2asn


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Get all the assignations of an IP.')
    parser.add_argument("-i", "--ip", required=True, type=str,
            help='IP address [127.0.0.1].')
    parser.add_argument("-d", "--debug", action="store_true",
            help='Enable debug mode (raise an exception if an IP is invalid).')
    args = parser.parse_args()

    ip = args.ip.strip()

    if args.debug:
        ip2asn.skip_exception = False
    first_date = None
    last_date = None
    prec_asn = None
    prec_block = None
    ip2asn.prepare_keys(ip)
    for entry in ip2asn.history():
        if entry is not None:
            date, asn, block = entry
            if first_date is None:
                last_date = date
                first_date = date
                prec_asn = asn
                prec_block = block
            elif prec_asn == asn and prec_block == block:
                first_date = date
            else:
                print first_date, last_date, prec_asn, prec_block
                last_date = date
                first_date = date
                prec_asn = asn
                prec_block = block
    if first_date is not None:
        print first_date, last_date, prec_asn, prec_block
