#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse

from ip_asn_history import api as ip2asn


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Get all the assignations of an IP.')
    parser.add_argument("-i", "--ip", required=True, type=str, help='IP address [127.0.0.1].')
    args = parser.parse_args()

    ip = args.ip.strip()

    ip2asn.prepare_keys(ip)
    for entry in ip2asn.history():
        if entry is not None:
            date, asn, block = entry
            print date, asn, block
